/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DecisionQpcCcRowDTO { 
    id: number;
    referenceDecisionConseil: string;
    numero: string;
    dateDecision: string;
    origineQpc: string;
    matiere: string;
    dispositifDecisionCc: string;
    traitementEffetsPasses: string;
    motifInconstitutionnalite: string;
    qualiteDemandeur: string;
    identiteDemandeur: string;
}

