/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DroitLiberteDTO } from './droitLiberteDTO';


export interface DecisionFiltrageQpcDTO { 
    id: number;
    ordreJuridictionnel: DecisionFiltrageQpcDTO.OrdreJuridictionnelEnum;
    juridiction: DecisionFiltrageQpcDTO.JuridictionEnum;
    chambreSousSection: string;
    numeroChambresReunies: string;
    niveauFiltrage: DecisionFiltrageQpcDTO.NiveauFiltrageEnum;
    origineJuridictionnelleQpc: string;
    niveauCompetence: string;
    dateFiltrage: string;
    formationJugement: string;
    reference: string;
    numeroDecision: string;
    referenceDispositionsContestees: string;
    loiOrigineDisposition: string;
    matiere: string;
    qualiteDemandeur: string;
    qualitePreciseDemandeur: string;
    identiteDemandeur: string;
    decisionRenvoi: string;
    decisionNonRenvoi: string;
    applicationTheorieChangementCirconstances: string;
    nombreDroitsNonMentionnes: string;
    autresRemarques: string;
    motsCles: string;
    createdAt: Date;
    updatedAt: Date;
    droitsLibertes: Array<DroitLiberteDTO>;
}
export namespace DecisionFiltrageQpcDTO {
    export type OrdreJuridictionnelEnum = 'JUDICIAIRE' | 'ADMINISTRATIF';
    export const OrdreJuridictionnelEnum = {
        Judiciaire: 'JUDICIAIRE' as OrdreJuridictionnelEnum,
        Administratif: 'ADMINISTRATIF' as OrdreJuridictionnelEnum
    };
    export type JuridictionEnum = 'CONSEIL_ETAT' | 'COUR_DE_CASSATION';
    export const JuridictionEnum = {
        ConseilEtat: 'CONSEIL_ETAT' as JuridictionEnum,
        CourDeCassation: 'COUR_DE_CASSATION' as JuridictionEnum
    };
    export type NiveauFiltrageEnum = 'NONE' | 'PREMIER_ET_DERNIER' | 'DEUXIEME_FILTRAGE';
    export const NiveauFiltrageEnum = {
        None: 'NONE' as NiveauFiltrageEnum,
        PremierEtDernier: 'PREMIER_ET_DERNIER' as NiveauFiltrageEnum,
        DeuxiemeFiltrage: 'DEUXIEME_FILTRAGE' as NiveauFiltrageEnum
    };
}


