/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Requête de recherche pour les décisions de filtrage QPC
 */
export interface DecisionFiltrageQpcSearchRequest { 
    numeroDecision: string;
    reference: string;
    juridictions: Array<DecisionFiltrageQpcSearchRequest.JuridictionsEnum>;
    niveauxFiltrage: Array<DecisionFiltrageQpcSearchRequest.NiveauxFiltrageEnum>;
    dateFiltrageFrom: string;
    dateFiltrageTo: string;
    formationsJugement: Array<string>;
    chambresSousSectionIds: Array<number>;
    numerosChambresReuniesIds: Array<number>;
    applicationTheorieChangementCirconstancesIds: Array<number>;
    originesJuridictionnellesQpc: Array<string>;
    matieresIds: Array<number>;
    droitsLibertesIds: Array<number>;
    codes: Array<string>;
}
export namespace DecisionFiltrageQpcSearchRequest {
    export type JuridictionsEnum = 'CONSEIL_ETAT' | 'COUR_DE_CASSATION';
    export const JuridictionsEnum = {
        ConseilEtat: 'CONSEIL_ETAT' as JuridictionsEnum,
        CourDeCassation: 'COUR_DE_CASSATION' as JuridictionsEnum
    };
    export type NiveauxFiltrageEnum = 'NONE' | 'PREMIER_ET_DERNIER' | 'DEUXIEME_FILTRAGE';
    export const NiveauxFiltrageEnum = {
        None: 'NONE' as NiveauxFiltrageEnum,
        PremierEtDernier: 'PREMIER_ET_DERNIER' as NiveauxFiltrageEnum,
        DeuxiemeFiltrage: 'DEUXIEME_FILTRAGE' as NiveauxFiltrageEnum
    };
}


