/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DecisionQpcCcSearchRequest { 
    origineQpcId?: number;
    qualiteDemandeurId?: number;
    typeDispositionLegislativeId?: number;
    matiereId?: number;
    dispositifDecisionCcId?: number;
    traitementEffetsPassesId?: number;
    oraliteId?: number;
    qualiteTiersInterventionId?: number;
    reserveIncompetenceConseilId?: number;
}

