/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DroitLiberteDTO } from './droitLiberteDTO';


export interface DecisionQpcCcDTO { 
    id: number;
    referenceDecisionConseil: string;
    numero: string;
    dateDecision: string;
    origineQpc: string;
    referenceDecisionTransmission: string;
    qualiteDemandeur: string;
    identiteDemandeur: string;
    dispositionsLegislativesContestees: string;
    typeDispositionLegislative: string;
    matiere: string;
    dispositifDecisionCc: string;
    dateAbrogationDifferee: string;
    delaiAvantAbrogationMois: number;
    traitementEffetsPasses: string;
    nombreMembresSieges: number;
    demandeRecusation: number;
    deport: number;
    nomMembreDeporteOuRecuse: string;
    oralite: string;
    applicationTheorieChangementCirconstances: boolean;
    nombreDroitsLibertesInvoques: number;
    nombreInterventionsAdmises: number;
    qualiteTiersIntervention: string;
    nombrePersonnesPhysiques: number;
    identitePersonnesPhysiques: string;
    nombreAssociations: number;
    identiteAssociations: string;
    nombreEntreprises: number;
    identiteEntreprises: string;
    nombreSyndicatsApOp: number;
    identiteSyndicatsApOp: string;
    nombreCollectivitesTerritoriales: number;
    identiteCollectivites: string;
    reserveOpportunite: boolean;
    reserveIncompetenceConseil: string;
    priseEnCompteInterpretationJurisprudentielle: boolean;
    techniquesControle: string;
    motifInconstitutionnalite: string;
    autresRemarques: string;
    caractereNotableDecision: boolean;
    createdAt: Date;
    updatedAt: Date;
    droitsLibertes: Array<DroitLiberteDTO>;
}

