/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SettingsDTO { 
    id: number;
    categorie: SettingsDTO.CategorieEnum;
    nom: string;
    description?: string;
    valeur: string;
    type: SettingsDTO.TypeEnum;
    nomEnum: string;
    updatedAt: Date;
    updatedById: number;
    updatedByNom: string;
    updatedByPrenom: string;
}
export namespace SettingsDTO {
    export type CategorieEnum = 'GENERAL';
    export const CategorieEnum = {
        General: 'GENERAL' as CategorieEnum
    };
    export type TypeEnum = 'STRING' | 'NUMBER' | 'DATE' | 'BOOLEAN';
    export const TypeEnum = {
        String: 'STRING' as TypeEnum,
        Number: 'NUMBER' as TypeEnum,
        Date: 'DATE' as TypeEnum,
        Boolean: 'BOOLEAN' as TypeEnum
    };
}


